### ISSUE TITLE
More than one minor value?

### ISSUE THREAD

**Issue by rauschma** [tc39-transfer/proposal-measure#1]
* Could there ever be more than one minor value?
  * I’m thinking of the following but I’m not sure if they are use cases for `Measure`: hours-minutes-seconds and degrees-minutes-seconds
* If yes, then `.value` could become an Array with one or more elements and `.minorValue` could be removed.

**Comment by ben-allen** [comment]
Currently there's no plans for mixed units with more than one minor value. However, this is an artifact of Measure having originally emerged from Smart Units, which only needs foot-and-inch, stone-and-pound, pound-and-ounce, and meter-and-centimeter. That said, the revision I'm currently working on does in fact use an array rather than separate major/minor unit properties, firstly because Measure has a lot of use beyond that original context, secondly because it's on the whole cleaner.

**Comment by TheOneTheOnlyJJ** [comment]
I believe a method similar to the `split` [method from UnitMath](https://github.com/ericman314/UnitMath?tab=readme-ov-file#unit-conversion) would make the most sense, as it would allow for custom unit minor values to be specified.

**Comment by ben-allen** [comment]
updated version committed
